entry = input(": ")
print(80*"=")
print("O tipo dele é?.......",type(entry))
print("É Número?............",entry.isnumeric())
print("É Alfabetico?........",entry.isalpha())
print("É Alfanumerico?......",entry.isalnum())
print("É Decimal?...........",entry.isdecimal())
print("É Maiusculu?.........",entry.isupper())
print("É Menusculu?.........",entry.islower())
print("É Captalizado?.......",entry.istitle())
print("É ascii?.............",entry.isascii())
print(80*"=")
